# Generated by Django 5.2.7 on 2025-11-20 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=260, unique=True),
        ),
        migrations.CreateModel(
            name='UserOTPCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True, max_length=6)),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
