# Generated by Django 5.2.7 on 2025-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username_userotpcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpcodes',
            name='code',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
